---
AWSTemplateFormatVersion: 2010-09-09
Description: MediaWiki CF-Temp

Parameters:
  KeyName:
    Description: Choose the key
    Type: AWS::EC2::KeyPair::KeyName
    
  AmiToUse:
    Description: Allowed AMI
    Type: AWS::EC2::Image::Id
    AllowedValues:
      - ami-0c1a7f89451184c8b
  VpcCidr:
    Description: The cidr for the VPC
    Type: String
    Default: 10.150.0.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/24)$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/24
  AppName:
    Type: String
    MaxLength: 4
    Description: Add four alphabet word which reperesent the application hosted on EC2
    ConstraintDescription: Must be meaningful & in lowercase and not more than 4 alphabets
  EC2InstanceName:
    Type: String
    MinLength: 9
    MaxLength: 14
    Description: Provide EC2 Inastance Name
    AllowedPattern: '[A-Z][A-Z0-9-]*'
    ConstraintDescription: Must be  meaningful and in uppercase and not more than 14 alphabets
  DBInstanceName:
    Description: The RDS instace name
    Type: String
    MinLength: '1'
    MaxLength: '48'
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: must begin with an alphabet and contain only alphabets characters or special character(-). 
  DBName:
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '24'
    AllowedPattern: '[a-z][a-z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Ec2 Configuration Parameters
        Parameters:
          - KeyName
          - EC2InstanceName
          - AmiToUse
      -
        Label:
          default: VPC Parameters
        Parameters:
          - VpcCidr
          - AppName
      -
        Label:
          default: RDS MYSQL Configuration
        Parameters:
          - DBInstanceName
          - DBName
          - DBUser
          - DBPassword
    ParameterLabels:
      DBName:
        default: (Only Lowercase)Must begin with a letter and contain only alphanumeric characters.
      DBInstanceName:
        default: (Only Lowercase)Must begin with a letter and contain only alphanumeric characters and - .
      EC2InstanceName:
        default: (Only Uppercase)Must be 9 charcters min.  
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: #Provide S3 Object URL of vpc.yaml template
      Parameters:  
        VpcCidr: !Ref VpcCidr 
        AppName: !Ref AppName 
      TimeoutInMinutes: 10
  SSHSGStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: #Provide S3 Object URL of ssh-sg.yaml template
      Parameters:  
        VPCId: !GetAtt VPCStack.Outputs.VpcId 
        ApplicationName: !Ref AppName 
      TimeoutInMinutes: 5
  HTTPSGStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: #Provide S3 Object URL of http-sg.yaml template.
      Parameters:  
        VPCId: !GetAtt VPCStack.Outputs.VpcId 
        ApplicationName: !Ref AppName 
      TimeoutInMinutes: 5
  RDSSGStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: #Provide S3 Object URL of rds-sg.yaml template
      Parameters:  
        VPCId: !GetAtt VPCStack.Outputs.VpcId 
        ApplicationName: !Ref AppName
        VPCBlock: !Ref VpcCidr
      TimeoutInMinutes: 5
  
  RDSStack:
    DependsOn: RDSSGStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: #Provide S3 Object URL of rds.yaml template.
      Parameters:
        DBSubnet1: !GetAtt VPCStack.Outputs.PvtSubnetId
        DBSubnet2: !GetAtt VPCStack.Outputs.PubSubnetId
        ApplicationName: !Ref AppName
        AZName: !GetAtt VPCStack.Outputs.PvtSubnetAz
        DBInstanceName: !Ref DBInstanceName
        DBName: !Ref DBName
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        VPCSG: !GetAtt RDSSGStack.Outputs.RDSGroupId
      TimeoutInMinutes: 15


  MediaWikiVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiToUse
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !GetAtt SSHSGStack.Outputs.SSHGroupId
        - !GetAtt HTTPSGStack.Outputs.HTTPGroupId
      SubnetId: !GetAtt VPCStack.Outputs.PubSubnetId
      UserData:
        Fn::Base64: |
            #!/bin/bash
            sudo apt update -y
            sudo apt install -y apache2
            sudo apt install -y php php-apcu php-intl php-mbstring php-xml php-mysql
            sudo wget -P /tmp https://releases.wikimedia.org/mediawiki/1.36/mediawiki-1.36.0.tar.gz
            sudo tar zxf /tmp/mediawiki-1.36.0.tar.gz
            sudo rm -f /var/www/html/index.html
            sudo cp -R mediawiki-1.36.0/* /var/www/html/
      Tags:
        -
          Key: Name
          Value: !Ref EC2InstanceName
Outputs:
  AppURL:
    Description: Application URL to access
    Value: !Sub 'http://${MediaWikiVMInstance.PublicDnsName}:8080/index.php'
  NameOfDB:
    Description: Name of DB
    Value: !Ref 'DBName'
  DBUserName:
   Description: DB user name
   Value: !Ref 'DBUser'
  RDSDBPort:
    Description: DB port number
    Value: !GetAtt RDSStack.Outputs.DBPort
  RDSEndPoint:
    Value: !GetAtt RDSStack.Outputs.EndPoint    
...            